### ISSUE TITLE
rpcompletion: list index out of range

### ISSUE THREAD

**Issue by guillaume-gricourt** [brsynth/rptools#36]
Error thrown by rpcompletion

```bash
Job in error state.. tool_id: rptools_rpcompletion, exit_code: 1, stderr: [32mrptools 6.4.1 (rpcompletion)
[0m
[32mUsing MetaNetX 4.4[0m
[32mDownloading cache[0m[32m OK[0m
[32mLoading cache in memory[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m OK[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/rptools/rpcompletion/__main__.py", line 125, in <module>
    _cli()
  File "/usr/local/lib/python3.10/site-packages/rptools/rpcompletion/__main__.py", line 57, in _cli
    pathways = rp_completion(
  File "/usr/local/lib/python3.10/site-packages/rptools/rpcompletion/rpcompletion.py", line 109, in rp_completion
    __rp2paths_compounds_in_cache(
  File "/usr/local/lib/python3.10/site-packages/rptools/rpcompletion/rpcompletion.py", line 314, in __rp2paths_compounds_in_cache
    smiles = row[1]
IndexError: list index out of range
```

Encountered with Galaxy, not reproduced locally.
Related to the cache ?

Related to https://github.com/brsynth/galaxytools/pull/180 and https://github.com/galaxyproject/tools-iuc/pull/4980

**Comment by guillaume-gricourt** [comment]
Docker command line run by planemo
```
docker run -e "GALAXY_SLOTS=$GALAXY_SLOTS" -e "GALAXY_MEMORY_MB=$GALAXY_MEMORY_MB" -e "GALAXY_MEMORY_MB_PER_SLOT=$GALAXY_MEMORY_MB_PER_SLOT" -e "HOME=$HOME" -e "_GALAXY_JOB_HOME_DIR=$_GALAXY_JOB_HOME_DIR" -e "_GALAXY_JOB_TMP_DIR=$_GALAXY_JOB_TMP_DIR" -e "TMPDIR=$TMPDIR" -e "TMP=$TMP" -e "TEMP=$TEMP" --name ef2c4e77f53a4691a9ab9df2d79a8dbd -v "$_GALAXY_JOB_TMP_DIR:$_GALAXY_JOB_TMP_DIR:rw" -v "$TMPDIR:$TMPDIR:rw" -v "$TMP:$TMP:rw" -v "$TEMP:$TEMP:rw" -v /tmp/tmpcwai9bsp/galaxy-dev:/tmp/tmpcwai9bsp/galaxy-dev:ro -v /tmp/tmpcwai9bsp/galaxy-dev/lib/galaxy/datatypes/converters:/tmp/tmpcwai9bsp/galaxy-dev/lib/galaxy/datatypes/converters:ro -v /tmp/tmpcwai9bsp/job_working_directory/000/5:/tmp/tmpcwai9bsp/job_working_directory/000/5:ro -v /tmp/tmpcwai9bsp/job_working_directory/000/5/outputs:/tmp/tmpcwai9bsp/job_working_directory/000/5/outputs:rw -v /tmp/tmpcwai9bsp/job_working_directory/000/5/configs:/tmp/tmpcwai9bsp/job_working_directory/000/5/configs:rw -v /tmp/tmpcwai9bsp/job_working_directory/000/5/working:/tmp/tmpcwai9bsp/job_working_directory/000/5/working:rw -v /tmp/tmpcwai9bsp/files:/tmp/tmpcwai9bsp/files:ro -v /tmp/tmpcwai9bsp/galaxy-dev/tool-data:/tmp/tmpcwai9bsp/galaxy-dev/tool-data:ro -v /home/runner/work/galaxytools/galaxytools:/home/runner/work/galaxytools/galaxytools:rw -v /home/runner/work/galaxytools/galaxytools/tools/rptools/test-data:/home/runner/work/galaxytools/galaxytools/tools/rptools/test-data:ro --cpus ${GALAXY_SLOTS:-1} -w /tmp/tmpcwai9bsp/job_working_directory/000/5/working --rm --user 1001:127 quay.io/biocontainers/python:3.7--1 /bin/bash /tmp/tmpcwai9bsp/job_working_directory/000/5/tool_script.sh > '../outputs/tool_stdout' 2> '../outputs/tool_stderr'; return_code=$?; echo $return_code > /tmp/tmpcwai9bsp/job_working_directory/000/5/galaxy_5.ec; cd '/tmp/tmpcwai9bsp/job_working_directory/000/5'; 
```
From [wrapper test](https://github.com/brsynth/galaxytools/actions/runs/7928354689/job/21646490499?pr=180)
